version: '3.8'
services:
  opensearch:
    image: opensearchproject/opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - compatibility.override_main_response_version=true
    ports:
      - "9200:9200"
      - "9600:9600"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
